# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python with Maven

on: [push]
  #schedule:
    # 定时执行，Runs at 17:00 UTC every day
    #- cron:  '0 17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run Python Application
      run: 
        python main.py ${{ secrets.EncryptKey  }}
        
    - name: Commit files
      run: |
         git config --local user.email "yingguqing@gmail.com"
         git config --local user.name "yingguqing"
         git add test.log
         #git add bing-wallpaper.json
         git commit -m "update readme.md"
         
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN  }}
         branch: main
         
         
